### ISSUE TITLE
Cleaning up localStorage

### ISSUE THREAD

**Issue by quanganhtran** [zalando/oauth2-client-js#17]
Remembering a request will create an entry in localStorage with the key as the concatenation of provider ID and state (uuid)
Only when the user completes the login flow, the entry is cleaned automatically by the library. If the user drops out of the login process and comes back later, a new request will be remembered and the old entry remains, thus gradually fill up localStorage

Could you give a recommended solution for this?

**Comment by prayerslayer** [comment]
If that happens, it's a bug. The storage is supposed to [clear every entry](https://github.com/zalando/oauth2-client-js/blob/master/src/storage/local-storage.js#L36) with your chosen prefix after a successful login.

Could you provide an example to reproduce?

**Comment by quanganhtran** [comment]
@prayerslayer Thank you for the timely response
Upon inspecting the code, I notice that the cleaning up was implemented in the recent 0.0.16, which is not yet available on npm

**Comment by quanganhtran** [comment]
Thank you for the timely response

I realized I have been using the wrong package https://www.npmjs.com/package/oauth2-client-js which only includes up to release 0.0.15 (storage starts cleaning up every entry since 0.0.16) instead of https://www.npmjs.com/package/@zalando/oauth2-client-js

I apologize for the inconvenience
