### ISSUE TITLE
Create TypeScript declaration files

### ISSUE THREAD

**Issue by lapanti** [zalando/oauth2-client-js#19]
As a user of TypeScript I would really like to be able to use this library with strong typing.

If it's okay with you guys I am willing to try and make the declaration files

**Comment by fragsalat** [comment]
:+1:  Tell me if you need help :)

**Comment by lapanti** [comment]
Great :) I'll start working on it

**Comment by liamdawson** [comment]
I notice you have #21 open - you're still waiting on feedback and a testing approach, yeah?

**Comment by lapanti** [comment]
@liamdawson yes exactly :)

**Comment by fragsalat** [comment]
So the typings looked good to me but I have actually no clue how a test setup looks like since I don't use typescript. 
The only idea I would have would be to run basic unit tests with typescript and assert on the data types but this would not make that much sense.
