### ISSUE TITLE
Request: Update the NPM package to include new types and removed dependency of node-uuid

### ISSUE THREAD

**Issue by lapanti** [zalando/oauth2-client-js#22]

**Comment by LeoAref** [comment]
@Lapanti This PR https://github.com/zalando/oauth2-client-js/pull/20 should close this issue, right?

**Comment by lapanti** [comment]
was the NPM package updated with the contents of #20

**Comment by LeoAref** [comment]
So it's still open to include new types

**Comment by lapanti** [comment]
I mean that the types and dependency have been fixed, the question is about including them in the **npm package**

**Comment by mamacdon** [comment]
@fragsalat are you able to publish an updated version to npm? 

It is currently still at 0.0.15 (see https://www.npmjs.com/package/oauth2-client-js)

**Comment by fragsalat** [comment]
Done. Now I see that the mail was for this comment^^
