### ISSUE TITLE
README.md is wrong

### ISSUE THREAD

**Issue by sttevan88** [zalando/oauth2-client-js#25]
var response = google.parse(window.location.href);

Should use window.location.hash instead of window.location.href

**Comment by lasomethingsomething** [comment]
Thanks for the note, @sttevan88. Do you want to make a PR to fix it?

**Comment by sttevan88** [comment]
Sure, no problem

**Comment by LeoAref** [comment]
@sttevan88 Are you still planing to create PR? thanks!

**Comment by sttevan88** [comment]
Oh sorry, I can, its just super busy now before vacations :/

Marko Jokic

On Fri 23. Jun 2017 at 17:48 Muhammad Aref

<
mailto:Muhammad Aref <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/sttevan88
Are you still planing to create PR? thanks!

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/zalando/oauth2-client-js/issues/25#issuecomment-310701972
, or
