### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by mamacdon** [zalando/oauth2-client-js#26]
The most recent version of this library published to npmjs.org is v0.0.15, which is from May 2015. Releases
v0.0.16 and v0.0.17 are tagged in the source repo, but they were never published.

Can we please get a new version published to npm? Thanks.

**Comment by fragsalat** [comment]
Sry that I forgot that.
I'm wondering why I received the mail for this issue today and not before 24 days.

This is done now.
