### ISSUE TITLE
Clean up localStorage

### ISSUE THREAD

**Issue by jans510** [zalando/oauth2-client-js#4]
After retrieving the access token, the client should forget the state, stored in the localStorage. This doesn't seem to work always (open https://yourturn.stups.zalan.do/ and look into the localStorage in the Browser's console, I have 83 state objects stored). Could you implement some sort of cleanup? In one of our projects I use the following: 

```
let localStorage = window.localStorage;
for (let [key] of Object.entries(localStorage)) {
        if (key.startsWith(provider.id)) {
            window.localStorage.removeItem(key);
        }
}
```

**Comment by prayerslayer** [comment]
Yeah, I remember I noticed this too but then forgot :sob: Basically we could put your code after a successful flow, we don't need the others afterwards.

**Comment by prayerslayer** [comment]
Released under `0.0.16`. The provider will now empty its part of the storage after a successful request.

**Comment by jans510** [comment]
Cool, thanks :smiley: 
But isn't this a too radical solution, you clean the whole local storage now (also other values set by the application). I would recommend to only delete items beginning with the provider id (as in my snippet), so (hopefully) only state object are deleted.

**Comment by prayerslayer** [comment]
Yes, was a bit careless late in the evening. Fix is on the way.

**Comment by prayerslayer** [comment]
See #6

**Comment by jans510** [comment]
Cool, thanks for the quick fix

**Comment by prayerslayer** [comment]
I better fix deleting all your data quickly :scream:
