### ISSUE TITLE
Failing responses lead to orphaned remembered requests

### ISSUE THREAD

**Issue by faboweb** [zalando/oauth2-client-js#8]
If a request fails, like when the auth-endpoint is not available, the remembered request will stay in localstorage. Doesn't it make sense to clear of all remembered request if one succeeds?

**Comment by prayerslayer** [comment]
Hmm actually that is what's supposed to happen.

We empty the store after successful response: https://github.com/zalando/oauth2-client-js/blob/master/src/provider.js#L108
Which means all keys with your prefix are deleted: https://github.com/zalando/oauth2-client-js/blob/master/src/storage/local-storage.js#L32

Are you using the latest version?

**Comment by prayerslayer** [comment]
Any news on this issue? I'd like to close it :)

**Comment by prayerslayer** [comment]
Closing because no response for over a year 😭
